import turtle
wn=turtle.Screen()
t=turtle.Turtle()
t.shape("turtle")
t.color("blue")
wn.bgcolor("black")
t.up()
t.stamp()
for i in range(10):
    t.forward(70)
    t.stamp()
    t.backward(70)
    t.right(36)
    t.forward(100)
    t.stamp()
    t.backward(100)
    t.right(36)
    t.forward(150)
    t.stamp()
    t.backward(150)
    t.right(36)
wn.exitonclick()